<?php
/**
 * Created by PhpStorm.
 * User: zhaoyu
 * Date: 2019/6/8
 * Time: 7:37 PM
 */

namespace app\controllers;


use app\models\Common;
use yii\web\Controller;

class CurrentlimitController extends Controller
{
    public $userid;

    public function beforeAction($action)
    {
        //限流措施 令牌桶算法
        $this->userid = rand(1,100).time().rand(1,999999);
        if( !$this->tokenBucket() ){
            Common::addLog('limit.log',$this->userid.' 访问失败',1);
        }
        Common::addLog('limit.log',$this->userid.' 访问成功');


        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex(){
        echo 1111;
        die;
    }

    //获取当前时间戳（毫秒）
    function microtime_float()
    {
        list($usec, $sec) = explode(" ", microtime());
        return ((float)$usec + (float)$sec);
    }

    function tokenBucket(): bool
    {
        $redis = \Yii::$app->redis;
        $r = 5;  //每秒投放令牌数
        $c = 20;  //桶总容量

        $lock = $redis->set('lock',1,'EX',60,'NX');
        if( !$lock ){
            return $this->tokenBucket();
        }
        $w = $redis->get('w')?:0;   //桶剩余容量,初始值为满容量
        $preTime = $redis->get('preTime')?:0;   //前一个请求的时间点，初始值为0
        $nowTime = $this->microtime_float();  //当前请求时间点

        $w = min($c,intval($w+($nowTime-$preTime)*$r));//当前剩余容量

        $redis->set('preTime',$nowTime,'EX',3600);
        $redis->set('w',$w,'EX',3600);

        Common::addLog('limit.log',$this->userid.'_'.$preTime.'_'.$nowTime.'_'.$w);

        if( $w>0 ){
            $redis->decr('w');
            $redis->del('lock');
            return true;
        }else{
            $redis->del('lock');
            return false;
        }
    }

}